#!/bin/bash

echo -n "Podaj teskt "
read TEKST

echo -n "Podaj wyrazenie regularne " 
read WYRAZENIE

echo -n "Podaj tekst zastepujacy " 
read ZASTEPUJACY

echo Wynik: `echo $TEKST | sed -e "s/$WYRAZENIE/$ZASTEPUJACY/"`



